name: Code Analysis

on:
  [push]

jobs:

  does-not-contain-secrets:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: zricethezav/gitleaks-action@master

  has-no-merge-conflicts:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: olivernybroe/action-conflict-finder@v1.1


  has-no-file-or-folder-case-sensitivity-issues:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: credfeto/action-case-checker@master

  raise-todo-issues:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: alstr/todo-to-issue-action@master
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "// TODO"
          COMMENT_MARKER: "//"
        id: "todo"