name: "Dependabot: Rebase"
on:
  push:
    branches:
      - main
  release:
    types: [published]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true


jobs:
  auto-rebase:
    runs-on: [self-hosted, linux, build]

    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    timeout-minutes: 5
    steps:
      - name: "Check Required Secrets"
        shell: bash
        run: |
          if [ -z "${{secrets.SOURCE_PUSH_TOKEN}}" ]; then
            echo "::error::SOURCE_PUSH_TOKEN is required but not set"
            exit 1
          fi

      - name: "Setup Job"
        uses: ./.github/actions/setup-job

      - name: "Rebase"
        uses: bbeesley/gha-auto-dependabot-rebase@v1.5.225
        env:
          GITHUB_TOKEN: ${{secrets.SOURCE_PUSH_TOKEN}}
