name: PR Update
on:
  pull_request:
    types:
      - opened
      - edited
      - ready_for_review
      - reopened
      - unassigned
    branches:
      - master

jobs:
  info:
    if: ${{ endsWith(github.repository , '-template') }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Branch: ${{ github.head_ref }}"
        echo "Base Branch: ${{ github.base_ref }}"
        echo "Repo: ${{ github.repository }}"
        echo "Owner: ${{ github.repository_owner }}"
        echo "Assigned: ${{ github.event.assignees }}"
        echo "Event: ${{ toJSON( github.event ) }}"

  add-pr-label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true

  assign-to-creator:
    runs-on: ubuntu-latest
    steps:
    - uses: thomaseizinger/assign-pr-creator-action@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
