name: Auto PR Creation
on:
  push:
    branches-ignore:
    - master
    - main
    - "release/**"
    - "hotfix/**"
    - "feature/**"

jobs:
  pull-request:
    runs-on: [self-hosted, linux]

    steps:
    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE
    - uses: jwalton/gh-find-current-pr@v1.3.0
      id: findPr

    - if: ${{ steps.findPr.outputs.number == '' }}
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        token: ${{ secrets.SOURCE_PUSH_TOKEN }}

    - if: ${{ steps.findPr.outputs.number != '' }}
      run: |
        echo "Pull request already exists with id: ${{ steps.findPr.outputs.number }}"
        echo "URL: https://github.com/${{github.repository}}/pull/${{ steps.findPr.outputs.number }}"

    - if: ${{ steps.findPr.outputs.number == '' }}
      id: pr-template
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.github/PULL_REQUEST_TEMPLATE.md

    - if: ${{ steps.findPr.outputs.number == '' }}
      run: |
        echo COMMIT_MSG=`git log -1 --pretty=%B` >> $GITHUB_ENV

    - if: ${{ steps.findPr.outputs.number == '' }}
      id: open-pr
      uses: repo-sync/pull-request@v2.6
      with:
        source_branch: ""                     # If blank, default: triggered branch
        destination_branch: "main"            # If blank, default: master
        pr_assignee: "${{ github.actor }}"    # Comma-separated list (no spaces)
        pr_label: "auto-pr"                   # Comma-separated list (no spaces)
        pr_draft: true                        # Creates pull request as draft
        pr_title: "${{ env.COMMIT_MSG }}"
        pr_body: "${{ steps.pr-template.outputs.content }}"
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - if: ${{ steps.findPr.outputs.number == '' }}
      name: output-url
      run: echo ${{steps.open-pr.outputs.pr_url}}

    - if: ${{ steps.findPr.outputs.number == '' }}
      name: output-number
      run: |
          echo ${{steps.open-pr.outputs.pr_number}}
          echo "GITHUB_EVENT_PATH={'pull_request': ${{steps.open-pr.outputs.pr_number}} }"
          echo "GITHUB_EVENT_PATH={'pull_request': ${{steps.open-pr.outputs.pr_number}} }" >> $GITHUB_ENV

    - if: ${{ steps.findPr.outputs.number == '' }}
      name: output-has-changed-files
      run: echo ${{steps.open-pr.outputs.has_changed_files}}

    # NEED TO SET github.context.payload.pull_request TO BE THE pr NUMBER
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        sync-labels: true

    - uses: colpal/actions-clean@v1
      if: ${{ always() }} # To ensure this step runs even when earlier steps fail
