name: "Repo: Update Labels"

on:
  push:
    branches:
      - main
    paths:
      - '.github/labels.yml'
      - '.github/workflows/update-labels.yml'

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: read


jobs:

  update-labels-config:

    runs-on: [self-hosted, linux, build]

    permissions:
      issues: write  # for crazy-max/ghaction-github-labeler to create, rename, update

    steps:
      - name: "Check Required Secrets"
        shell: bash
        run: |
          if [ -z "${{secrets.SOURCE_PUSH_TOKEN}}" ]; then
            echo "::error::SOURCE_PUSH_TOKEN is required but not set"
            exit 1
          fi

      - name: "Setup Job"
        uses: ./.github/actions/setup-job

      - name: "Checkout Source"
        uses: actions/checkout@v6.0.2
        with:
          clean: true
          fetch-depth: 1
          token: ${{secrets.SOURCE_PUSH_TOKEN}}

      - name: "Update Github label config"
        if: success()
        uses: crazy-max/ghaction-github-labeler@v6.0.0
        with:
          github-token: ${{secrets.SOURCE_PUSH_TOKEN}}
          yaml-file: .github/labels.yml
          skip-delete: false
          dry-run: false
          exclude: |
            help*
            *issue
